// Copyright 2026 Glenn Lewis. All rights reserved.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

package conversation

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"
)

// TestStripAttachmentsFromFile verifies that StripAttachmentsFromFile rewrites
// an LXMF message container with its file/image/audio attachment fields
// removed, byte-for-byte matching the Python NomadNet
// ConversationMessage.strip_attachments_from_file output. Fixtures under
// testdata/strip were generated by running the verbatim Python logic.
func TestStripAttachmentsFromFile(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name string
		// makeDir controls whether the per-message attachment directory is
		// staged. When false, strip must be a no-op (the directory the Python
		// logic keys on does not exist).
		makeDir bool
	}{
		{"nostamp", true},
		{"stamp", true},
		{"nostamp_nodir", false},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			fixtureName := tc.name
			if !tc.makeDir {
				fixtureName = "nostamp"
			}

			base := tempDir(t)
			attachmentPath := filepath.Join(base, "attachments")

			if tc.makeDir {
				srcAttDir := filepath.Join("testdata", "strip", fixtureName+"_attachments")
				if err := copyTree(srcAttDir, attachmentPath); err != nil {
					t.Fatal(err)
				}
			}

			inputBytes, err := os.ReadFile(filepath.Join("testdata", "strip", fixtureName+"_input.bin"))
			if err != nil {
				t.Fatal(err)
			}

			inputPath := filepath.Join(base, "msg.bin")
			if err := os.WriteFile(inputPath, inputBytes, 0o644); err != nil {
				t.Fatal(err)
			}

			if err := StripAttachmentsFromFile(inputPath, attachmentPath); err != nil {
				t.Fatalf("StripAttachmentsFromFile: %v", err)
			}

			got, err := os.ReadFile(inputPath)
			if err != nil {
				t.Fatal(err)
			}

			if tc.makeDir {
				expected, err := os.ReadFile(filepath.Join("testdata", "strip", fixtureName+"_expected.bin"))
				if err != nil {
					t.Fatal(err)
				}
				if !bytes.Equal(got, expected) {
					t.Errorf("stripped output differs from Python reference:\n got  (%v bytes): %x\n want (%v bytes): %x",
						len(got), got, len(expected), expected)
				}
			} else {
				// No attachment directory staged: strip must leave the file unchanged.
				if !bytes.Equal(got, inputBytes) {
					t.Errorf("strip modified file despite missing attachment directory:\n got  (%v bytes): %x\n want (%v bytes): %x",
						len(got), got, len(inputBytes), inputBytes)
				}
			}
		})
	}
}

// copyTree recursively copies the src directory tree into dst, preserving
// relative layout.
func copyTree(src, dst string) error {
	return filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		target := filepath.Join(dst, rel)
		if info.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		return os.WriteFile(target, data, 0o644)
	})
}
